import {useEffect,useMemo,useState} from 'react';
import {supabase} from './supabase.js';
import {Flame,Footprints,Plus,Trash2,Home,History,Settings,Check} from 'lucide-react';

const DEFAULT={calorieGoal:2000,stepGoal:8000,foods:[],steps:[]};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>dateKey(new Date());
const fmtDate=k=>new Date(k+'T00:00:00').toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'});
const fmtTime=x=>new Date(x).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});

function Card({children}){return <section className="card">{children}</section>}
function Nav({view,setView}){return <nav className="nav">{[['today','Hoy',Home],['history','Historial',History],['settings','Ajustes',Settings]].map(([id,label,I])=><button className={view===id?'active':''} key={id} onClick={()=>setView(id)}><I size={17}/>{label}</button>)}</nav>}
function Progress({value,goal,type}){const pct=Math.min(100,goal?value/goal*100:0);return <div><div className="progress"><span className={type==='steps'?'steps':''} style={{width:`${pct}%`}}/></div><small>{Math.max(0,goal-value).toLocaleString('es-ES')} {type==='steps'?'pasos':'kcal'} restantes</small></div>}

export default function App({session}){
 const userId=session.user.id,date=today(); const [view,setView]=useState('today'); const [day,setDay]=useState(null); const [history,setHistory]=useState([]); const [food,setFood]=useState(''); const [kcal,setKcal]=useState(''); const [steps,setSteps]=useState(''); const [goals,setGoals]=useState(DEFAULT); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{(async()=>{const {data}=await supabase.from('days').select('calorie_goal,step_goal,foods,steps').eq('user_id',userId).eq('day_key',date).maybeSingle();const d=data?{calorieGoal:data.calorie_goal,stepGoal:data.step_goal,foods:data.foods||[],steps:data.steps||[]}:DEFAULT;setDay(d);setGoals(d)})()},[userId,date]);
 useEffect(()=>{if(!day)return;(async()=>{setSaving(true);await supabase.from('days').upsert({user_id:userId,day_key:date,calorie_goal:day.calorieGoal,step_goal:day.stepGoal,foods:day.foods,steps:day.steps,updated_at:new Date().toISOString()},{onConflict:'user_id,day_key'});setSaving(false)})()},[day]);
 useEffect(()=>{if(view!=='history')return;(async()=>{const arr=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=dateKey(d);if(k===date){arr.push({key:k,steps:day?.steps.reduce((a,x)=>a+x.amount,0)||0,kcal:day?.foods.reduce((a,x)=>a+x.kcal,0)||0});continue}const {data}=await supabase.from('days').select('foods,steps').eq('user_id',userId).eq('day_key',k).maybeSingle();arr.push({key:k,steps:data?.steps?.reduce((a,x)=>a+x.amount,0)||0,kcal:data?.foods?.reduce((a,x)=>a+x.kcal,0)||0})}setHistory(arr)})()},[view,day,userId,date]);
 if(!day)return <div className="loading">Cargando Zancada…</div>;
 const consumed=day.foods.reduce((a,x)=>a+x.kcal,0), totalSteps=day.steps.reduce((a,x)=>a+x.amount,0);
 function addFood(e){e.preventDefault();const n=Number(kcal);if(!food.trim()||!n||n<1){setMessage('Introduce una comida y unas kcal válidas.');return}setMessage('');setDay(d=>({...d,foods:[...d.foods,{id:uid(),name:food.trim(),kcal:Math.round(n),time:new Date().toISOString()}]}));setFood('');setKcal('')}
 function addSteps(n){n=Number(n);if(!n||n<1)return;setDay(d=>({...d,steps:[...d.steps,{id:uid(),amount:Math.round(n),time:new Date().toISOString()}]}))}
 function saveGoals(e){e.preventDefault();setDay(d=>({...d,calorieGoal:Math.max(1,Number(goals.calorieGoal)||d.calorieGoal),stepGoal:Math.max(1,Number(goals.stepGoal)||d.stepGoal)}));setMessage('Objetivos guardados.')}
 return <div className="app"><header><div className="brand"><b>Z</b><strong>Zancada</strong></div><div className="header-right"><span>{fmtDate(date)}</span><button onClick={()=>supabase.auth.signOut()}>Salir</button></div></header><div className="layout"><Nav view={view} setView={setView}/><main>
 {view==='today'&&<><p className="intro">{new Date().getHours()<13?'Buenos días':new Date().getHours()<20?'Buenas tardes':'Buenas noches'}. Así va tu día.</p><div className="grid2"><Card><div className="icon orange"><Flame/></div><h2>{consumed.toLocaleString('es-ES')} <small>/ {day.calorieGoal.toLocaleString('es-ES')} kcal</small></h2><Progress value={consumed} goal={day.calorieGoal} type="kcal"/></Card><Card><div className="icon green"><Footprints/></div><h2>{totalSteps.toLocaleString('es-ES')} <small>/ {day.stepGoal.toLocaleString('es-ES')} pasos</small></h2><Progress value={totalSteps} goal={day.stepGoal} type="steps"/>{totalSteps>=day.stepGoal&&<p className="success"><Check size={14}/> Objetivo cumplido</p>}</Card></div><div className="grid2 forms"><section><h3>Registrar comida</h3><form onSubmit={addFood}><input placeholder="Tortilla de patata" value={food} onChange={e=>setFood(e.target.value)}/><input placeholder="kcal" type="number" min="1" value={kcal} onChange={e=>setKcal(e.target.value)}/><button><Plus size={15}/>Añadir</button></form>{message&&<p className="message">{message}</p>}<div>{[...day.foods].sort((a,b)=>new Date(b.time)-new Date(a.time)).map(f=><div className="row" key={f.id}><span>{f.name}<small>{fmtTime(f.time)}</small></span><b>{f.kcal} kcal</b><button className="delete" onClick={()=>setDay(d=>({...d,foods:d.foods.filter(x=>x.id!==f.id)}))}><Trash2 size={14}/></button></div>)}</div></section><section><h3>Registrar pasos</h3><div className="chips">{[500,1000,2000].map(n=><button key={n} onClick={()=>addSteps(n)}><Plus size={13}/>{n}</button>)}</div><form onSubmit={e=>{e.preventDefault();addSteps(steps);setSteps('')}}><input placeholder="Cantidad manual" type="number" min="1" value={steps} onChange={e=>setSteps(e.target.value)}/><button><Plus size={15}/>Añadir</button></form>{[...day.steps].sort((a,b)=>new Date(b.time)-new Date(a.time)).map(s=><div className="row" key={s.id}><small>{fmtTime(s.time)}</small><b>+{s.amount.toLocaleString('es-ES')}</b><button className="delete" onClick={()=>setDay(d=>({...d,steps:d.steps.filter(x=>x.id!==s.id)}))}><Trash2 size={14}/></button></div>)}</section></div></>}
 {view==='history'&&<><h1>Historial</h1><p className="muted">Tus últimos 7 días de actividad.</p><Card><div className="bars">{history.map(h=><div className="barwrap" key={h.key}><div className="bar" style={{height:`${Math.max(5,Math.min(100,h.steps/Math.max(day.stepGoal,1)*100))}%`}}/><small>{new Date(h.key+'T00:00:00').toLocaleDateString('es-ES',{weekday:'short'}).slice(0,2)}</small></div>)}</div></Card><Card>{[...history].reverse().map((h,i)=><div className="row" key={h.key}><span>{h.key===date?'Hoy':fmtDate(h.key)}</span><span>{h.steps.toLocaleString('es-ES')} pasos · {h.kcal} kcal</span></div>)}</Card></>}
 {view==='settings'&&<><h1>Ajustes</h1><p className="muted">Define tus metas diarias y gestiona tu sesión.</p><Card><form onSubmit={saveGoals} className="settings"><label>Meta de calorías<input type="number" min="1" value={goals.calorieGoal} onChange={e=>setGoals(g=>({...g,calorieGoal:e.target.value}))}/></label><label>Meta de pasos<input type="number" min="1" value={goals.stepGoal} onChange={e=>setGoals(g=>({...g,stepGoal:e.target.value}))}/></label><button>Guardar cambios</button>{saving&&<small>Guardando…</small>}{message&&<p className="success">{message}</p>}</form></Card><Card><p className="muted">Esto borra comidas y pasos registrados hoy. Tus metas no se modifican.</p><button className="danger" onClick={()=>setDay(d=>({...d,foods:[],steps:[]}))}>Restablecer el día de hoy</button></Card></>}
 </main></div></div>
}
